-- Create Format Mapping Table
CREATE TABLE IF NOT EXISTS tender.format_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  format_id bigint REFERENCES tender.tender_formats(id) ON DELETE CASCADE,
  category_id bigint REFERENCES tender.tender_categories(id),
  project_type_id bigint REFERENCES tender.project_types(id),
  state text NOT NULL,
  city text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  life_cycle_status tender.life_cycle_status DEFAULT 'ACTIVE',
  CONSTRAINT format_mappings_pkey PRIMARY KEY (id)
);

-- Index for fast filtering
CREATE INDEX IF NOT EXISTS idx_format_mappings_filter ON tender.format_mappings (category_id, project_type_id, state, city);
