-- Create Schema if not exists
CREATE SCHEMA IF NOT EXISTS tender;

-- Create Enum Type for Life Cycle Status (if not exists)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'life_cycle_status' AND typnamespace = 'tender'::regnamespace) THEN
        CREATE TYPE tender.life_cycle_status AS ENUM ('ACTIVE', 'INACTIVE', 'DELETED', 'BLOCKED');
    END IF;
END $$;

-- Roles Table Fixes
CREATE TABLE IF NOT EXISTS tender.roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  role_name text NOT NULL,
  updated_at timestamp with time zone NULL,
  life_cycle_status tender.life_cycle_status NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT Role_pkey PRIMARY KEY (id),
  CONSTRAINT Role_role_name_key UNIQUE (role_name)
);

-- Ensure life_cycle_status has default and is not null in roles
ALTER TABLE tender.roles ALTER COLUMN life_cycle_status SET DEFAULT 'ACTIVE';
UPDATE tender.roles SET life_cycle_status = 'ACTIVE' WHERE life_cycle_status IS NULL;
ALTER TABLE tender.roles ALTER COLUMN life_cycle_status SET NOT NULL;

-- Users Table Fixes
CREATE TABLE IF NOT EXISTS tender.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL,
  email text NOT NULL,
  password text NOT NULL,
  phone_number text NULL,
  display_id text NOT NULL,
  updated_at timestamp with time zone NULL,
  life_cycle_status tender.life_cycle_status NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT User_pkey PRIMARY KEY (id),
  CONSTRAINT users_display_id_key UNIQUE (display_id),
  CONSTRAINT users_email_key UNIQUE (email)
);

-- Add missing columns to users
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='tender' AND table_name='users' AND column_name='password') THEN
        ALTER TABLE tender.users ADD COLUMN password text;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='tender' AND table_name='users' AND column_name='email') THEN
        ALTER TABLE tender.users ADD COLUMN email text;
    END IF;
END $$;

-- Update users constraints
UPDATE tender.users SET password = 'CHANGE_ME' WHERE password IS NULL;
ALTER TABLE tender.users ALTER COLUMN password SET NOT NULL;
UPDATE tender.users SET email = 'temp@example.com' WHERE email IS NULL;
ALTER TABLE tender.users ALTER COLUMN email SET NOT NULL;
ALTER TABLE tender.users ALTER COLUMN life_cycle_status SET DEFAULT 'ACTIVE';
UPDATE tender.users SET life_cycle_status = 'ACTIVE' WHERE life_cycle_status IS NULL;
ALTER TABLE tender.users ALTER COLUMN life_cycle_status SET NOT NULL;

-- User Role Access Table
CREATE TABLE IF NOT EXISTS tender.user_role_access (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  role_id bigint NULL,
  updated_at timestamp with time zone NULL,
  user_id bigint NULL,
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_role_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES tender.users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES tender.roles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Pages Table
CREATE TABLE IF NOT EXISTS tender.pages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  page_name text NOT NULL,
  CONSTRAINT Pages_pkey PRIMARY KEY (id),
  CONSTRAINT pages_page_name_key UNIQUE (page_name)
);

-- User/Role Page Access Table
CREATE TABLE IF NOT EXISTS tender.user_page_access (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id bigint NULL,
  role_id bigint NULL,
  page_id bigint NULL,
  updated_at timestamp with time zone NULL,
  can_create boolean NOT NULL DEFAULT false,
  can_view boolean NOT NULL DEFAULT false,
  can_edit boolean NOT NULL DEFAULT false,
  can_delete boolean NOT NULL DEFAULT false,
  CONSTRAINT user_page_access_pkey PRIMARY KEY (id),
  CONSTRAINT user_page_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES tender.users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT user_page_access_role_id_fkey FOREIGN KEY (role_id) REFERENCES tender.roles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT user_page_access_page_id_fkey FOREIGN KEY (page_id) REFERENCES tender.pages (id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Seed initial roles with explicit life_cycle_status
INSERT INTO tender.roles (role_name, life_cycle_status) 
VALUES ('ADMIN', 'ACTIVE'), ('USER', 'ACTIVE'), ('MANAGER', 'ACTIVE')
ON CONFLICT (role_name) DO NOTHING;
