create table tender.pages (
  id bigint generated by default as identity not null,
  page_name text not null,
  constraint Pages_pkey primary key (id),
  constraint pages_page_name_key unique (page_name)
) TABLESPACE pg_default;