CREATE TABLE IF NOT EXISTS tender.project_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  record_uid bigint NOT NULL,
  type_name text NOT NULL,
  created_by bigint REFERENCES tender.users(id),
  updated_by bigint REFERENCES tender.users(id),
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NULL,
  life_cycle_status tender.life_cycle_status NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT project_types_pkey PRIMARY KEY (id)
);

ALTER TABLE tender.project_types
  ADD COLUMN IF NOT EXISTS record_uid bigint;

CREATE SEQUENCE IF NOT EXISTS tender.project_types_record_uid_seq;

ALTER TABLE tender.project_types
  ALTER COLUMN record_uid SET DEFAULT nextval('tender.project_types_record_uid_seq');

ALTER TABLE tender.project_types
  ADD COLUMN IF NOT EXISTS created_by bigint REFERENCES tender.users(id);

ALTER TABLE tender.project_types
  ADD COLUMN IF NOT EXISTS updated_by bigint REFERENCES tender.users(id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'project_types_name_key'
      AND conrelid = 'tender.project_types'::regclass
  ) THEN
    ALTER TABLE tender.project_types DROP CONSTRAINT project_types_name_key;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS project_types_active_name_uq
ON tender.project_types (lower(btrim(type_name)))
WHERE life_cycle_status = 'ACTIVE';

INSERT INTO tender.project_types (record_uid, type_name)
SELECT *
FROM (
  VALUES
    (1, 'Architectural'),
    (2, 'Sewage'),
    (3, 'Waste Management')
) AS seed_data(record_uid, type_name)
WHERE NOT EXISTS (
  SELECT 1
  FROM tender.project_types pt
  WHERE lower(btrim(pt.type_name)) = lower(btrim(seed_data.type_name))
);
