CREATE TABLE IF NOT EXISTS tender.project_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  type_name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NULL,
  life_cycle_status tender.life_cycle_status NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT project_types_pkey PRIMARY KEY (id),
  CONSTRAINT project_types_name_key UNIQUE (type_name)
);


INSERT INTO tender.project_types (type_name)
VALUES
('Architectural'),
('Sewage'),
('Waste Management'),
('Civil Works'),
('Electrical')
ON CONFLICT (type_name) DO NOTHING;
