create table tender.roles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  role_name text null,
  updated_at timestamp with time zone null,
  life_cycle_status tender.life_cycle_status not null,
  constraint Role_pkey primary key (id),
  constraint Role_role_name_key unique (role_name)
) TABLESPACE pg_default;