-- Tenders Table
CREATE TABLE IF NOT EXISTS tender.tenders (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL,
  description text NOT NULL,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  budget numeric(15, 2) NOT NULL,
  status text NOT NULL DEFAULT 'OPEN', -- OPEN, CLOSED, AWARDED
  created_by bigint REFERENCES tender.users(id),
  updated_at timestamp with time zone NULL,
  CONSTRAINT Tenders_pkey PRIMARY KEY (id)
);

-- Bids Table
CREATE TABLE IF NOT EXISTS tender.bids (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  tender_id bigint NOT NULL REFERENCES tender.tenders(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES tender.users(id) ON DELETE CASCADE,
  bid_amount numeric(15, 2) NOT NULL,
  proposal text NOT NULL,
  status text NOT NULL DEFAULT 'PENDING', -- PENDING, ACCEPTED, REJECTED
  updated_at timestamp with time zone NULL,
  CONSTRAINT Bids_pkey PRIMARY KEY (id),
  CONSTRAINT unique_user_tender_bid UNIQUE (tender_id, user_id)
);
