
CREATE TABLE IF NOT EXISTS tender.tender_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  record_uid bigint NOT NULL,
  category_name text NOT NULL,
  category_description text NULL,
  created_by bigint REFERENCES tender.users(id),
  updated_by bigint REFERENCES tender.users(id),
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NULL,
  life_cycle_status tender.life_cycle_status NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT tender_categories_pkey PRIMARY KEY (id)
);

ALTER TABLE tender.tender_categories
  ADD COLUMN IF NOT EXISTS record_uid bigint;

CREATE SEQUENCE IF NOT EXISTS tender.tender_categories_record_uid_seq;

ALTER TABLE tender.tender_categories
  ALTER COLUMN record_uid SET DEFAULT nextval('tender.tender_categories_record_uid_seq');

ALTER TABLE tender.tender_categories
  ADD COLUMN IF NOT EXISTS created_by bigint REFERENCES tender.users(id);

ALTER TABLE tender.tender_categories
  ADD COLUMN IF NOT EXISTS updated_by bigint REFERENCES tender.users(id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'tender_categories_name_key'
      AND conrelid = 'tender.tender_categories'::regclass
  ) THEN
    ALTER TABLE tender.tender_categories DROP CONSTRAINT tender_categories_name_key;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS tender_categories_active_name_uq
ON tender.tender_categories (lower(btrim(category_name)))
WHERE life_cycle_status = 'ACTIVE';

CREATE UNIQUE INDEX IF NOT EXISTS tender_categories_active_description_uq
ON tender.tender_categories (lower(btrim(category_description)))
WHERE life_cycle_status = 'ACTIVE'
  AND category_description IS NOT NULL
  AND btrim(category_description) <> '';

INSERT INTO tender.tender_categories (record_uid, category_name, category_description)
SELECT *
FROM (
  VALUES
    (1, 'RFP', 'Request For Proposal')
) AS seed_data(record_uid, category_name, category_description)
WHERE NOT EXISTS (
  SELECT 1
  FROM tender.tender_categories tc
  WHERE lower(btrim(tc.category_name)) = lower(btrim(seed_data.category_name))
);
