
CREATE TABLE IF NOT EXISTS tender.tender_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  category_name text NOT NULL,
  category_description text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NULL,
  life_cycle_status tender.life_cycle_status NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT tender_categories_pkey PRIMARY KEY (id),
  CONSTRAINT tender_categories_name_key UNIQUE (category_name)
);


INSERT INTO tender.tender_categories (category_name, category_description)
VALUES
('NIT', 'Notice Inviting Tender'),
('RFP', 'Request For Proposal'),
('EOI', 'Expression of Interest'),
('RFQ', 'Request For Quotation')
ON CONFLICT (category_name) DO NOTHING;
