-- Create Tender Formats Table
CREATE TABLE IF NOT EXISTS tender.tender_formats (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  format_name text NOT NULL, -- e.g. ANNEXURE-1
  format_title text NOT NULL, -- e.g. LETTER OF APPLICATION
  category_id bigint REFERENCES tender.tender_categories(id), -- Linked to EOI, RFP etc.
  project_type_id bigint REFERENCES tender.project_types(id), -- Linked to Sewage, Water etc.
  state text NULL,
  city text NULL,
  template_html text NOT NULL, -- Stores the HTML structure
  schema_json jsonb NULL, -- Stores field definitions if needed for dynamic forms
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  life_cycle_status tender.life_cycle_status DEFAULT 'ACTIVE',
  CONSTRAINT tender_formats_pkey PRIMARY KEY (id)
);
