create table tender.user_role_access (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  role_id bigint null,
  updated_at timestamp with time zone null,
  user_id bigint null,
  constraint user_roles_pkey primary key (id),
  constraint user_role_access_user_id_fkey foreign KEY (user_id) references tender.users (id) on update CASCADE on delete CASCADE,
  constraint user_roles_role_id_fkey foreign KEY (role_id) references tender.roles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;