create table tender.users (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  email text null,
  phone_number numeric null,
  display_id text not null,
  updated_at timestamp with time zone null,
  life_cycle_status tender.life_cycle_status not null,
  constraint User_pkey primary key (id),
  constraint users_display_id_key unique (display_id)
) TABLESPACE pg_default;