create table tender.user_page_access (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id bigint null,
  role_id bigint null,
  updated_at timestamp with time zone null,
  can_create boolean not null default false,
  can_view boolean not null default false,
  can_edit boolean not null default false,
  can_delete boolean not null default false,
  constraint user_page_access_pkey primary key (id),
  constraint user_page_access_role_id_fkey foreign KEY (role_id) references tender.roles (id) on update CASCADE on delete CASCADE,
  constraint user_page_access_user_id_fkey foreign KEY (user_id) references tender.users (id) on update CASCADE on delete CASCADE,
  constraint user_page_access_check check (false)
) TABLESPACE pg_default;